config/routes.rb
Rails.application.routes.draw do
  resources :stocks
  root to: "stocks#index"
  devise_for :users

end

app/models/stock.rb
class Stock < ActiveRecord::Base
  has_many :children, :class_name => "Stock", :foreign_key => :parent_id
  belongs_to :parent, :class_name => "Stock", :foreign_key => :parent_id
  
  has_many :stock_prices
     
  def self.search(search)
    where("roi IS NOT NULL AND (ticker LIKE? OR name LIKE ?)", "#{search}%", "%#{search}%")
  end   
     
  def self.find_by_ticker(ticker_symbol)
    where(ticker: ticker_symbol).first
  end 
  
  def self.new_from_lookup(ticker_symbol)
    looked_up_stock = StockQuote::Stock.quote(ticker_symbol)
    return nil unless looked_up_stock.name
    
    new_Stock = new(ticker: looked_up_stock.symbol, name: looked_up_stock.name,
                      last_price: looked_up_stock.last_trade_price_only)
    new_Stock
  end
   
  def self.refresh_price 
    Stock.all.each do |v|
      s.last_price  = StockQuote::Stock.quote(s.ticker).last_trade_price_only
      s.save
    end
  end
  
  def self.get_price_history(ticker_symbol)
    @s=Stock.find_by_ticker(ticker_symbol)
    StockPrice.where("stock_id = ?", @s.id).delete_all

    begin
      history = StockQuote::Stock.history(ticker_symbol, Date.today-1.years, Date.today)
      first_record = true
      history.each do |sqh|
        if first_record == true
          @s.last_price = sqh.close
          @s.pricing_date = sqh.date
          first_record = false
        end
        sp = StockPrice.new
        sp.stock_id = @s.id
        sp.trade_date = sqh.date
        # sp.volume = sqh.volume
        sp.open = sqh.open
        sp.high = sqh.high
        sp.low  = sqh.low
        sp.close = sqh.close
        sp.adj_close = sqh.adj_close
        sp.save
      end
    rescue StandardError
      history = nil
    end
    @s.save
end 

def self.calc_stats(ticker_symbol)  
    @s=Stock.find_by_ticker(ticker_symbol)
    prev_adj_close = -1 
    roi_sum = 0.0
    @s.stock_prices.sort_by { |m| m[:trade_date] }.each do |row|
      if prev_adj_close > 0 
                 puts row.roi
         row.roi = (row.adj_close - prev_adj_close) / prev_adj_close
         puts row.roi
         roi_sum = roi_sum + Math.log(1+row.roi.to_f)
      end
      prev_adj_close = row.adj_close
      row.save
    end   

    # stock_price = @s.stock_prices.where('roi IS NOT NULL').extend(DescriptiveStatistics)
    stock_price = @s.stock_prices.extend(DescriptiveStatistics)
    @s.no_of_prices = stock_price.number(&:roi)
    if @s.no_of_prices > 20
      @s.roi = Math.exp(roi_sum) - 1
      @s.risk = stock_price.standard_deviation(&:roi) * Math.sqrt(250) 
      @s.alpha = 0
      # @s.beta = 1.0
      if @s.parent_id
        @i = @s.parent
        @s.alpha = @s.roi.to_f - ( @s.risk * (@i.roi.to_f-0.02)/@i.risk ) - 0.02
      else
        alpha = 0 
      end 
      @s.sharpe = (@s.roi.to_f - 0.02)/@s.risk.to_f
    else
      @s.roi = nil
      @s.risk = nil
      @s.alpha = nil 
      @s.sharpe = nil 
     end
      @s.save     
   
  end  
  
  def self.benchmark(ticker_symbol)  
    require 'statsample'
    
    @a=Stock.find_by_ticker(ticker_symbol)
    @b=Stock.where(" id = 1" )
    
    @x = @a.StockPrice.order(:trade_date)
    @y = @b.StockPrice.order(:trade_date)
    
    ss_analysis("Statsample::Bivariate.correlation_matrix") do 
      ds=data_frame(@x, @y)
      cm=cor(ds) 
      summary(cm)
    end
   
  end 
  
  def self.get_prices
    stk = Stock.where(" parent_id is NULL ")
    stk.each do |row|
      get_price_history(row.ticker)
      calc_stats(row.ticker)
    end 
    stk = Stock.where(" parent_id is NOT NULL ")
    stk.each do |row|
      get_price_history(row.ticker)
      calc_stats(row.ticker)
    end      
  end   
  
  def self.set_index
    @s = Stock.where(id = 1)
    @s.parent_id = nil
    @s.save     
  end 
end

app/models/stock_price.rb
class StockPrice < ActiveRecord::Base
  belongs_to :stock
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  helper_method :sort_column, :sort_direction
  before_action :set_stock, only: [:show, :edit, :update, :destroy]

  def index
    if params[:search]
      @stocks = Stock.where(" parent_id is NOT NULL").search(params[:search]).order(sort_column + " " + sort_direction).paginate(:page => params[:page], :per_page => 20)
    else
      @stocks = Stock.where("roi is not null and parent_id is NOT NULL ").order(sort_column + " " + sort_direction).paginate(:page => params[:page], :per_page => 20)
    end
  end

  def search
    where("roi IS NOT NULL AND (ticker LIKE? OR name LIKE ?)", "#{search}%", "%#{search}%")
  end

  # GET /stocks
  # GET /stocks.json
  def chart
      @stocks = Stock.all
  end

  # GET /stocks/1
  # GET /stocks/1.json
  def show
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks
  # POST /stocks.json
  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to @stock, notice: 'Stock was successfully created.' }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1
  # PATCH/PUT /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to @stock, notice: 'Stock was successfully updated.' }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1
  # DELETE /stocks/1.json
  def destroy
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to stocks_url, notice: 'Stock was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    def sort_column
      Stock.column_names.include?(params[:sort]) ? params[:sort] : "name"
    end
    
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stock_params
      params.require(:stock).permit(:ticker, :name, :price, :pricing_date, :roi, :risk, :sharpe, :alpha)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, params.merge(:sort => column, :direction => direction, :page => nil), {:class => css_class}
  end
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ifa</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/stocks/_form.html.erb
<%= form_for(@stock) do |f| %>
  <% if @stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
      <% @stock.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ticker %><br>
    <%= f.text_field :ticker %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :last_price %><br>
    <%= f.text_field :last_price %>
  </div>
  <div class="field">
    <%= f.label :pricing_date %><br>
    <%= f.date_select :pricing_date %>
  </div>
  <div class="field">
    <%= f.label :return %><br>
    <%= f.text_field :roi %>
  </div>
  <div class="field">
    <%= f.label :risk %><br>
    <%= f.text_field :risk %>
  </div>
  <div class="field">
    <%= f.label :sharpe %><br>
    <%= f.text_field :sharpe %>
  </div>
  <div class="field">
    <%= f.label :alpha %><br>
    <%= f.text_field :alpha %>
  </div>
  <div class="field">
    <%= f.label :parent_id %><br>
    <%= f.number_field :parent_id %>
  </div>
  <div class="field">
    <%= f.label :no_of_prices %><br>
    <%= f.number_field :no_of_prices %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stocks/edit.html.erb
<h1>Editing Stock</h1>

<%= render 'form' %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Stocks</h1>
    
<div class-"row">
    <div class="form form-group">
    <%= form_tag stocks_path, :method => 'get' do%>
        <p>
            <%= text_field_tag :search,  params[:search], placeholder: "Search text" %>
            <%= submit_tag "Wild Search", :name => nil %>
        </p>
    <% end %>
    </div>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= sortable "ticker" %></th>
      <th class="col-md-6"><%= sortable "name"   %></th>
      <th><%= sortable "last_price", "Price" %> </th>
      <th><%= sortable "roi", "Return" %></th>
      <th><%= sortable "risk"   %></th>
      <th><%= sortable "sharpe", "Sharpe" %></th>
      <th><%= sortable "alpha", "Alpha" %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stocks.each do |stock| %>
      <tr>
        <td style="text-align: center"><%= stock.ticker %></td>
        <td style="text-align: left"><%= stock.name %></td>
        <td style="text-align: right"><%= number_with_precision(stock.last_price, precision: 2) %></td>
        <td style="text-align: right"><%= number_to_percentage(stock.roi*100, precision: 1) %></td>
        <td style="text-align: right"><%= number_to_percentage(stock.risk*100, precision: 1) %></td>
        <td style="text-align: right"><%= number_with_precision(stock.sharpe, precision: 3) %></td>
        <td style="text-align: right"><%= number_to_percentage(stock.alpha*100, precision: 1) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= will_paginate @stocks %>

<br>

<%= link_to "logout", destroy_user_session_path, method: :delete %>

app/views/stocks/index_old.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Stocks</h1>

<table>
  <thead>
    <tr>
      <th>Ticker</th>
      <th>Name</th>
      <th>Last price</th>
      <th>Pricing date</th>
      <th>Return</th>
      <th>Risk</th>
      <th>Sharpe</th>
      <th>Alpha</th>
      <th>Parent</th>
      <th>No of prices</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stocks.each do |stock| %>
      <tr>
        <td><%= stock.ticker %></td>
        <td><%= stock.name %></td>
        <td><%= stock.last_price %></td>
        <td><%= stock.pricing_date %></td>
        <td><%= stock.roi %></td>
        <td><%= stock.risk %></td>
        <td><%= stock.sharpe %></td>
        <td><%= stock.alpha %></td>
        <td><%= stock.parent_id %></td>
        <td><%= stock.no_of_prices %></td>
        <td><%= link_to 'Show', stock %></td>
        <td><%= link_to 'Edit', edit_stock_path(stock) %></td>
        <td><%= link_to 'Destroy', stock, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stock', new_stock_path %>

app/views/stocks/new.html.erb
<h1>New Stock</h1>

<%= render 'form' %>

<%= link_to 'Back', stocks_path %>

app/views/stocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ticker:</strong>
  <%= @stock.ticker %>
</p>

<p>
  <strong>Name:</strong>
  <%= @stock.name %>
</p>

<p>
  <strong>Last price:</strong>
  <%= @stock.last_price %>
</p>

<p>
  <strong>Pricing date:</strong>
  <%= @stock.pricing_date %>
</p>

<p>
  <strong>Return:</strong>
  <%= @stock.roi %>
</p>

<p>
  <strong>Risk:</strong>
  <%= @stock.risk %>
</p>

<p>
  <strong>Sharpe:</strong>
  <%= @stock.sharpe %>
</p>

<p>
  <strong>Alpha:</strong>
  <%= @stock.alpha %>
</p>

<p>
  <strong>Parent:</strong>
  <%= @stock.parent_id %>
</p>

<p>
  <strong>No of prices:</strong>
  <%= @stock.no_of_prices %>
</p>

<%= link_to 'Edit', edit_stock_path(@stock) %> |
<%= link_to 'Back', stocks_path %>